font_family GeistMono Nerd Font Mono
font_size   13


disable_ligatures yes
enable_audio_bell no

shell zsh
shell_integration disabled

url_style curly

remember_windows_size         no
window_padding_width          30
cursor_blink_interval         0

background_opacity            0.30
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0


sync_to_monitor  no

# COLORS

foreground #353d40
background #303638
cursor #cccccc
color0 #303638
color1 #b64b35      --red
color2 #314730      --green
color3 #e1cb80      --yellow
color4 #0b4052      --blue
color5 #5e211f      --darkred
color6 #334d56      --turqoise
color7 #353d40
color8 #262a2b
color9 #5b4430      --brown
color10 #334d56     --turqoise
color11 #e1cb80     --yellow
color12 #0b4052     --blue
color13 #5e211f     --darkred
color14 #334d56     --turqoise
color15 #9c9fa6
selection_foreground #303638
selection_background #353d40

