font_family GeistMono Nerd Font Mono
font_size   13


disable_ligatures yes
enable_audio_bell no

shell zsh
shell_integration disabled

url_style curly

remember_windows_size         no
window_padding_width          30
cursor_blink_interval         0

background_opacity 0.7
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
confirm_os_window_close       0


sync_to_monitor  no

# COLORS

foreground #bcc0cc
background #4c4f69
cursor #cccccc
color0 #4c4f69
color1 #ff393c      --red
color2 #2a635d      --green
color3 #bfa801      --yellow
color4 #365e81      --blue
color5 #791924      --darkred
color6 #1a3f47      --turqoise
color7 #bcc0cc
color8 #393e48
color9 #ebcbc3      --brown
color10 #1a3f47     --turqoise
color11 #bfa801     --yellow
color12 #365e81     --blue
color13 #791924     --darkred
color14 #1a3f47     --turqoise
color15 #abb2bf
selection_foreground #4c4f69
selection_background #bcc0cc

